### ISSUE TITLE
media process needs support for date ranges

### ISSUE THREAD

**Issue by roncanepa** [iDigBio/idb-backend#102]
currently it only provides the ability for everything or "last 48 hours".

**Comment by roncanepa** [comment]
It also supports "since" but that doesn't cover all use cases.

**Comment by nrejack** [comment]
This is for the media fetching process?

**Comment by roncanepa** [comment]
Sort of.  The process is really two parts: 

1. mediaing-updatedb: look through postgres records, find urls that need to be fetched, create/update appropriate row
2. mediaing-get-media: go through the above rows and do the actual fetch

**Comment by roncanepa** [comment]
I'm looking at the underlying tables now to see if this is even feasible.

**Comment by nrejack** [comment]
I wouldn't worry about adding date ranges, that's not something we've ever needed to do in the past. Since this is a catch-up procedure we only ever move forward to the present date, not over a selected range in the past.

**Comment by roncanepa** [comment]
I'll run it as-is to do the bulk update and we'll see how it goes.

**Comment by roncanepa** [comment]
This also may end up being relevant for any kind of re-download scenario.

**Comment by danstoner** [comment]
Mediaing updatedb no longer runs as a service due to memory constraints / conflict with Indexing.  We now run a "full" on every ingestion run.
