### ISSUE TITLE
Check  v2 media upload for correct handling of 3d models

### ISSUE THREAD

**Issue by UnwashedMeme** [iDigBio/idb-backend#11]
From @godfoder w.r.t. the [media-appliance](https://github.com/iDigBio/idigbio-ingestion-tool)

> I also need to work on the documentation to indicate that this is really a _media_ appliance now, not just images. As it is coded, it should support Images (.jpg), Sound (.mp3), Video (.mp4), and possibly also 3d Models (.stl). I think there is an API bug preventing that last one from working, but the appliance side looks good.

We need to check that 3d models (`.stl` files) can be uploaded through the v2 media api correctly.

**Comment by UnwashedMeme** [comment]
I downloaded a sample stl fle from 

It isn't working well with python-magic that we're using.

```python
In [183]: magic.from_file('/tmp/ship.stl')
Out[183]: 'data'
```

**Comment by nrejack** [comment]
As the Media Appliance is no longer supported we will not be expanding the upload features.
