### ISSUE TITLE
Allow post URL only to new media api

### ISSUE THREAD

**Issue by UnwashedMeme** [iDigBio/idb-backend#13]
We had previously said the upload api should only allow a full upload or associating a new url with an existing etag.

We're now saying that they can post a new url only that should be entered into the media table where the regular mediaing process will then fetch it.  At some time later some other process will create the actual mediarecords.

**Comment by godfoder** [comment]
Also, posting a URL to the portal should clear the last status so the url is harvested again.

**Comment by UnwashedMeme** [comment]
From some other discussions we also decided that it must have a posted `type` and `mime`

**Comment by UnwashedMeme** [comment]
This is built, tested, deployed... I don't think there's anything left until we get bug reports.
