### ISSUE TITLE
idb datatables sub-command needs to be documented

### ISSUE THREAD

**Issue by nrejack** [iDigBio/idb-backend#154]
Need to document what this is used for and how to use it.

Current output from running `idb datatables`:
```
Usage: idb datatables [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  locality-data
  rights-strings
  taxon
```

**Comment by danstoner** [comment]
hmmm  some of these came into being from Alex's habit of testing module code in `main` (which isn't called under normal circumstances), and Nathan doing a conversion of "everything" he could find to Click.

I'll think about whether it is worth leaving some of them in (maybe just dump the tables / values to stdout) or remove the `datatables` command completely.

**Comment by danstoner** [comment]
See `idb/load_corrections.py` for how those modules are actually used.

There is a lot of old stuff hanging around in this part of the code base, references to local files that don't exist at the moment, etc.  :disappointed:
