### ISSUE TITLE
test_helpers_storage takes a long time to run

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#23]
When running py.test, the following takes a long time to run:

```tests/idb/test_helpers_storage.py ...```

Test suite should run quickly to encourage use.

Slow test suite discourages use.

**Comment by danstoner** [comment]
Assuming there isn't anything in test_helpers_storage that can be removed or optimized...

Does pytest provide tiers such as "quick" vs "full" ?

Should I just get in habit of running the subtests such as ```$ pytest tests/idigbio_ingestion``` ?

**Comment by godfoder** [comment]
The tests seem to be primarily slow due to the speed of ceph (setup, latency, processing time) operations, not to the actual speed of transfers.
We could build up a quick and slow suite, but I'd have to figure out if pytest gives us any helpers.

**Comment by UnwashedMeme** [comment]
Pytest lets you mark test and then only run tests that have that Mark.

What I tend to do in practice though is only run the subset of tests that
are around the functionality of the thing I'm working onperiod and then at
the end of the day I run the full Suite

**Comment by danstoner** [comment]
I believe the mode of running the "subset of tests around the functionality of the thing" is my immediate plan going forward. Our directory structure gives coarse granularity to these subsets already and of course individual test files can be run for more fine-grained operation.

Further reading on pytest markers:

https://docs.pytest.org/en/latest/mark.html


Closing.
