### ISSUE TITLE
docs on record diff strategy

### ISSUE THREAD

**Issue by jhpoelen** [iDigBio/idb-backend#42]
hey y'all!

I am trying to figure out the way the iDigBio ingestion process detects changes in existing records. I made some notes at https://github.com/bio-linker/organization/wiki/dwca-diff#idigbio . Before I continue, I was wondering whether there's some existing documentation on your change detection methods. 

Thanks!

**Comment by danstoner** [comment]
When a dataset is processed, each row is serialized to JSON and then a checksum is generated (etag) based on the content of the JSON blob itself.  There is a link between each unique identifier (recordID) and its associated etags.

When next the dataset is processed, a new etag for an existing recordID is an "update; a new etag without an existing recordID is a "create".

I believe most of the work happens in https://github.com/iDigBio/idb-backend/blob/master/idigbio_ingestion/db_check.py

**Comment by jhpoelen** [comment]
@danstoner thanks!
