### ISSUE TITLE
add trace as a log level to helpers/logger.py

### ISSUE THREAD

**Issue by roncanepa** [iDigBio/idb-backend#96]
the logger "helper" needs to be separated on its own, but meanwhile, trace is not implemented as a valid level and should be.

**Comment by danstoner** [comment]
I have heard you mention "trace" a few times but I'm not sure what you mean.

I am not aware of a `TRACE` logging level.

https://docs.python.org/3/library/logging.html#logging-levels

**Comment by roncanepa** [comment]
@danstoner a tracelog is a generic concept even if a language doesn't use the term specifically.  it's for "log everything in excruciating detail,"  which we're in need of.   So in this case, we'd either implement another level in the helper and stick it in an appropriate priority level as far as the system library is concerned, or we shift everything "up" one level in our current stuff and "info" becomes the new "debug."

I've had other places where I need extra output, but I can't put it under "debug" because then the logging will always be chock full of a level of detail we may not actually need 24/7.   It makes more sense to add an additional level than it does to change every script we have from `logging.debug` to `logging.info`.

**Comment by danstoner** [comment]
What I am doing for now is using `debug` level but only logging the truly excruciating detail when the special environment variable is set.  Could easily be renamed to be TRACE something instead of IDB_EXTRA_SERIOUS_DEBUG.

**Comment by danstoner** [comment]
I think `debug` would work fine for logging excruciating detail.

If this logging setup was working properly, `debug` should do what you need and we would only get debug messages when the code is run with `-vv` or `-vvv`.  And trying to add something new when the existing levels are not working well seems unlikely to succeed.

Sharing some more specific examples would definitely help other people understand where the roughest edges are or where we need to look at the existing loglevel settings.

**Comment by danstoner** [comment]
Stale.  Closing.
